import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from '../../components/Header';
import { SanityLive } from "@/sanity/lib/live";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import Footer from "../../components/Footer";
import SubHeader from "@/components/SubHeader";




export const metadata: Metadata = {
  title: "Shopr E-commerce",
  description: "Generated by Maheen Arif",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider  dynamic>

    
    <html lang="en">
      <body>
        {/* <div className="max-w-[90%] mx-auto "> */}

        
        {(await draftMode()).isEnabled && (
          <>
          <DisableDraftMode/>
          <VisualEditing/>
          </>
        )}
        <main>
          <Header/>
          <SubHeader/>
        {children}
        <Footer/>
        </main>
        <SanityLive/>
        {/* </div> */}
      </body>
    </html>
    </ClerkProvider>
  );
}
